<?php


namespace OpencartApi\ModelContainer\v3037;


use OpencartApi\Base\BaseModel;

/**
 * Trait OpencartModelsTrait
 *
 * @method \OpencartApi\Models\v3037\ModelCheckoutOrder getModelCheckoutOrder
 * @method \OpencartApi\Models\v3037\ModelCheckoutRecurring getModelCheckoutRecurring
 * @method \OpencartApi\Models\v3037\ModelCheckoutMarketing getModelCheckoutMarketing
 * @method \OpencartApi\Models\v3037\ModelToolImage getModelToolImage
 * @method \OpencartApi\Models\v3037\ModelToolOnline getModelToolOnline
 * @method \OpencartApi\Models\v3037\ModelToolUpload getModelToolUpload
 * @method \OpencartApi\Models\v3037\ModelSettingApi getModelSettingApi
 * @method \OpencartApi\Models\v3037\ModelSettingSetting getModelSettingSetting
 * @method \OpencartApi\Models\v3037\ModelSettingStore getModelSettingStore
 * @method \OpencartApi\Models\v3037\ModelSettingModule getModelSettingModule
 * @method \OpencartApi\Models\v3037\ModelSettingExtension getModelSettingExtension
 * @method \OpencartApi\Models\v3037\ModelSettingEvent getModelSettingEvent
 * @method \OpencartApi\Models\v3037\ModelAccountOrder getModelAccountOrder
 * @method \OpencartApi\Models\v3037\ModelAccountApi getModelAccountApi
 * @method \OpencartApi\Models\v3037\ModelAccountAddress getModelAccountAddress
 * @method \OpencartApi\Models\v3037\ModelAccountReward getModelAccountReward
 * @method \OpencartApi\Models\v3037\ModelAccountCustomer getModelAccountCustomer
 * @method \OpencartApi\Models\v3037\ModelAccountTransaction getModelAccountTransaction
 * @method \OpencartApi\Models\v3037\ModelAccountActivity getModelAccountActivity
 * @method \OpencartApi\Models\v3037\ModelAccountCustomerGroup getModelAccountCustomerGroup
 * @method \OpencartApi\Models\v3037\ModelAccountWishlist getModelAccountWishlist
 * @method \OpencartApi\Models\v3037\ModelAccountRecurring getModelAccountRecurring
 * @method \OpencartApi\Models\v3037\ModelAccountCustomField getModelAccountCustomField
 * @method \OpencartApi\Models\v3037\ModelAccountDownload getModelAccountDownload
 * @method \OpencartApi\Models\v3037\ModelAccountReturn getModelAccountReturn
 * @method \OpencartApi\Models\v3037\ModelAccountSearch getModelAccountSearch
 * @method \OpencartApi\Models\v3037\ModelCatalogCategory getModelCatalogCategory
 * @method \OpencartApi\Models\v3037\ModelCatalogManufacturer getModelCatalogManufacturer
 * @method \OpencartApi\Models\v3037\ModelCatalogProduct getModelCatalogProduct
 * @method \OpencartApi\Models\v3037\ModelCatalogReview getModelCatalogReview
 * @method \OpencartApi\Models\v3037\ModelCatalogInformation getModelCatalogInformation
 * @method \OpencartApi\Models\v3037\ModelExtensionFeedGoogleBase getModelExtensionFeedGoogleBase
 * @method \OpencartApi\Models\v3037\ModelExtensionCreditCardSquareup getModelExtensionCreditCardSquareup
 * @method \OpencartApi\Models\v3037\ModelExtensionModuleLaybuyLayout getModelExtensionModuleLaybuyLayout
 * @method \OpencartApi\Models\v3037\ModelExtensionModuleAmazonLogin getModelExtensionModuleAmazonLogin
 * @method \OpencartApi\Models\v3037\ModelExtensionModulePaypalSmartButton getModelExtensionModulePaypalSmartButton
 * @method \OpencartApi\Models\v3037\ModelExtensionAdvertiseGoogle getModelExtensionAdvertiseGoogle
 * @method \OpencartApi\Models\v3037\ModelExtensionTotalKlarnaFee getModelExtensionTotalKlarnaFee
 * @method \OpencartApi\Models\v3037\ModelExtensionTotalReward getModelExtensionTotalReward
 * @method \OpencartApi\Models\v3037\ModelExtensionTotalCoupon getModelExtensionTotalCoupon
 * @method \OpencartApi\Models\v3037\ModelExtensionTotalLowOrderFee getModelExtensionTotalLowOrderFee
 * @method \OpencartApi\Models\v3037\ModelExtensionTotalCredit getModelExtensionTotalCredit
 * @method \OpencartApi\Models\v3037\ModelExtensionTotalTax getModelExtensionTotalTax
 * @method \OpencartApi\Models\v3037\ModelExtensionTotalVoucherTheme getModelExtensionTotalVoucherTheme
 * @method \OpencartApi\Models\v3037\ModelExtensionTotalTotal getModelExtensionTotalTotal
 * @method \OpencartApi\Models\v3037\ModelExtensionTotalShipping getModelExtensionTotalShipping
 * @method \OpencartApi\Models\v3037\ModelExtensionTotalSubTotal getModelExtensionTotalSubTotal
 * @method \OpencartApi\Models\v3037\ModelExtensionTotalHandling getModelExtensionTotalHandling
 * @method \OpencartApi\Models\v3037\ModelExtensionTotalVoucher getModelExtensionTotalVoucher
 * @method \OpencartApi\Models\v3037\ModelExtensionFraudMaxmind getModelExtensionFraudMaxmind
 * @method \OpencartApi\Models\v3037\ModelExtensionFraudIp getModelExtensionFraudIp
 * @method \OpencartApi\Models\v3037\ModelExtensionFraudFraudlabspro getModelExtensionFraudFraudlabspro
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentPpBraintree getModelExtensionPaymentPpBraintree
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentKlarnaCheckout getModelExtensionPaymentKlarnaCheckout
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentPerpetualPayments getModelExtensionPaymentPerpetualPayments
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentPaypal getModelExtensionPaymentPaypal
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentFirstdata getModelExtensionPaymentFirstdata
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentNochex getModelExtensionPaymentNochex
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentLaybuy getModelExtensionPaymentLaybuy
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentLiqpay getModelExtensionPaymentLiqpay
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentSagepayDirect getModelExtensionPaymentSagepayDirect
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentCheque getModelExtensionPaymentCheque
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentDivido getModelExtensionPaymentDivido
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentFirstdataRemote getModelExtensionPaymentFirstdataRemote
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentBluepayHosted getModelExtensionPaymentBluepayHosted
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentWebPaymentSoftware getModelExtensionPaymentWebPaymentSoftware
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentSkrill getModelExtensionPaymentSkrill
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentWechatPay getModelExtensionPaymentWechatPay
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentTwocheckout getModelExtensionPaymentTwocheckout
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentCardconnect getModelExtensionPaymentCardconnect
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentPpStandard getModelExtensionPaymentPpStandard
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentFreeCheckout getModelExtensionPaymentFreeCheckout
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentPaymate getModelExtensionPaymentPaymate
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentSquareup getModelExtensionPaymentSquareup
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentPpExpress getModelExtensionPaymentPpExpress
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentPpPayflowIframe getModelExtensionPaymentPpPayflowIframe
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentBluepayRedirect getModelExtensionPaymentBluepayRedirect
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentWorldpay getModelExtensionPaymentWorldpay
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentRealexRemote getModelExtensionPaymentRealexRemote
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentCod getModelExtensionPaymentCod
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentEway getModelExtensionPaymentEway
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentCardinity getModelExtensionPaymentCardinity
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentSagepayUs getModelExtensionPaymentSagepayUs
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentAuthorizenetSim getModelExtensionPaymentAuthorizenetSim
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentPpPro getModelExtensionPaymentPpPro
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentPayza getModelExtensionPaymentPayza
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentG2apay getModelExtensionPaymentG2apay
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentPaypoint getModelExtensionPaymentPaypoint
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentAmazonLoginPay getModelExtensionPaymentAmazonLoginPay
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentGlobalpayRemote getModelExtensionPaymentGlobalpayRemote
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentGlobalpay getModelExtensionPaymentGlobalpay
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentAlipayCross getModelExtensionPaymentAlipayCross
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentKlarnaAccount getModelExtensionPaymentKlarnaAccount
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentPilibaba getModelExtensionPaymentPilibaba
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentSecuretradingPp getModelExtensionPaymentSecuretradingPp
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentBankTransfer getModelExtensionPaymentBankTransfer
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentPpProIframe getModelExtensionPaymentPpProIframe
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentKlarnaInvoice getModelExtensionPaymentKlarnaInvoice
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentSagepayServer getModelExtensionPaymentSagepayServer
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentAlipay getModelExtensionPaymentAlipay
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentAuthorizenetAim getModelExtensionPaymentAuthorizenetAim
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentSecuretradingWs getModelExtensionPaymentSecuretradingWs
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentPpPayflow getModelExtensionPaymentPpPayflow
 * @method \OpencartApi\Models\v3037\ModelExtensionPaymentRealex getModelExtensionPaymentRealex
 * @method \OpencartApi\Models\v3037\ModelExtensionShippingFedex getModelExtensionShippingFedex
 * @method \OpencartApi\Models\v3037\ModelExtensionShippingUsps getModelExtensionShippingUsps
 * @method \OpencartApi\Models\v3037\ModelExtensionShippingUps getModelExtensionShippingUps
 * @method \OpencartApi\Models\v3037\ModelExtensionShippingFree getModelExtensionShippingFree
 * @method \OpencartApi\Models\v3037\ModelExtensionShippingEcShip getModelExtensionShippingEcShip
 * @method \OpencartApi\Models\v3037\ModelExtensionShippingRoyalMail getModelExtensionShippingRoyalMail
 * @method \OpencartApi\Models\v3037\ModelExtensionShippingFlat getModelExtensionShippingFlat
 * @method \OpencartApi\Models\v3037\ModelExtensionShippingItem getModelExtensionShippingItem
 * @method \OpencartApi\Models\v3037\ModelExtensionShippingAuspost getModelExtensionShippingAuspost
 * @method \OpencartApi\Models\v3037\ModelExtensionShippingPilibaba getModelExtensionShippingPilibaba
 * @method \OpencartApi\Models\v3037\ModelExtensionShippingPickup getModelExtensionShippingPickup
 * @method \OpencartApi\Models\v3037\ModelExtensionShippingWeight getModelExtensionShippingWeight
 * @method \OpencartApi\Models\v3037\ModelExtensionShippingParcelforce48 getModelExtensionShippingParcelforce48
 * @method \OpencartApi\Models\v3037\ModelLocalisationZone getModelLocalisationZone
 * @method \OpencartApi\Models\v3037\ModelLocalisationLanguage getModelLocalisationLanguage
 * @method \OpencartApi\Models\v3037\ModelLocalisationReturnReason getModelLocalisationReturnReason
 * @method \OpencartApi\Models\v3037\ModelLocalisationCurrency getModelLocalisationCurrency
 * @method \OpencartApi\Models\v3037\ModelLocalisationCountry getModelLocalisationCountry
 * @method \OpencartApi\Models\v3037\ModelLocalisationOrderStatus getModelLocalisationOrderStatus
 * @method \OpencartApi\Models\v3037\ModelLocalisationLocation getModelLocalisationLocation
 * @method \OpencartApi\Models\v3037\ModelDesignBanner getModelDesignBanner
 * @method \OpencartApi\Models\v3037\ModelDesignLayout getModelDesignLayout
 * @method \OpencartApi\Models\v3037\ModelDesignTranslation getModelDesignTranslation
 * @method \OpencartApi\Models\v3037\ModelDesignTheme getModelDesignTheme
 * @method \OpencartApi\Models\v3037\ModelReportStatistics getModelReportStatistics
 * @method \OpencartApi\Models\v3037\AdminModelSaleOrder getAdminModelSaleOrder
 * @method \OpencartApi\Models\v3037\AdminModelSaleRecurring getAdminModelSaleRecurring
 * @method \OpencartApi\Models\v3037\AdminModelSaleVoucherTheme getAdminModelSaleVoucherTheme
 * @method \OpencartApi\Models\v3037\AdminModelSaleReturn getAdminModelSaleReturn
 * @method \OpencartApi\Models\v3037\AdminModelSaleVoucher getAdminModelSaleVoucher
 * @method \OpencartApi\Models\v3037\AdminModelToolImage getAdminModelToolImage
 * @method \OpencartApi\Models\v3037\AdminModelToolUpload getAdminModelToolUpload
 * @method \OpencartApi\Models\v3037\AdminModelToolBackup getAdminModelToolBackup
 * @method \OpencartApi\Models\v3037\AdminModelSettingSetting getAdminModelSettingSetting
 * @method \OpencartApi\Models\v3037\AdminModelSettingStore getAdminModelSettingStore
 * @method \OpencartApi\Models\v3037\AdminModelSettingModule getAdminModelSettingModule
 * @method \OpencartApi\Models\v3037\AdminModelSettingExtension getAdminModelSettingExtension
 * @method \OpencartApi\Models\v3037\AdminModelSettingEvent getAdminModelSettingEvent
 * @method \OpencartApi\Models\v3037\AdminModelSettingModification getAdminModelSettingModification
 * @method \OpencartApi\Models\v3037\AdminModelCatalogCategory getAdminModelCatalogCategory
 * @method \OpencartApi\Models\v3037\AdminModelCatalogAttributeGroup getAdminModelCatalogAttributeGroup
 * @method \OpencartApi\Models\v3037\AdminModelCatalogManufacturer getAdminModelCatalogManufacturer
 * @method \OpencartApi\Models\v3037\AdminModelCatalogOption getAdminModelCatalogOption
 * @method \OpencartApi\Models\v3037\AdminModelCatalogProduct getAdminModelCatalogProduct
 * @method \OpencartApi\Models\v3037\AdminModelCatalogRecurring getAdminModelCatalogRecurring
 * @method \OpencartApi\Models\v3037\AdminModelCatalogDownload getAdminModelCatalogDownload
 * @method \OpencartApi\Models\v3037\AdminModelCatalogAttribute getAdminModelCatalogAttribute
 * @method \OpencartApi\Models\v3037\AdminModelCatalogReview getAdminModelCatalogReview
 * @method \OpencartApi\Models\v3037\AdminModelCatalogFilter getAdminModelCatalogFilter
 * @method \OpencartApi\Models\v3037\AdminModelCatalogInformation getAdminModelCatalogInformation
 * @method \OpencartApi\Models\v3037\AdminModelMarketingCoupon getAdminModelMarketingCoupon
 * @method \OpencartApi\Models\v3037\AdminModelMarketingMarketing getAdminModelMarketingMarketing
 * @method \OpencartApi\Models\v3037\AdminModelExtensionFeedGoogleBase getAdminModelExtensionFeedGoogleBase
 * @method \OpencartApi\Models\v3037\AdminModelExtensionModulePaypalSmartButton getAdminModelExtensionModulePaypalSmartButton
 * @method \OpencartApi\Models\v3037\AdminModelExtensionAdvertiseGoogle getAdminModelExtensionAdvertiseGoogle
 * @method \OpencartApi\Models\v3037\AdminModelExtensionFraudMaxmind getAdminModelExtensionFraudMaxmind
 * @method \OpencartApi\Models\v3037\AdminModelExtensionFraudIp getAdminModelExtensionFraudIp
 * @method \OpencartApi\Models\v3037\AdminModelExtensionFraudFraudlabspro getAdminModelExtensionFraudFraudlabspro
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentPpBraintree getAdminModelExtensionPaymentPpBraintree
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentKlarnaCheckout getAdminModelExtensionPaymentKlarnaCheckout
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentPaypal getAdminModelExtensionPaymentPaypal
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentFirstdata getAdminModelExtensionPaymentFirstdata
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentLaybuy getAdminModelExtensionPaymentLaybuy
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentSagepayDirect getAdminModelExtensionPaymentSagepayDirect
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentDivido getAdminModelExtensionPaymentDivido
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentFirstdataRemote getAdminModelExtensionPaymentFirstdataRemote
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentBluepayHosted getAdminModelExtensionPaymentBluepayHosted
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentCardconnect getAdminModelExtensionPaymentCardconnect
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentSquareup getAdminModelExtensionPaymentSquareup
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentPpExpress getAdminModelExtensionPaymentPpExpress
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentPpPayflowIframe getAdminModelExtensionPaymentPpPayflowIframe
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentBluepayRedirect getAdminModelExtensionPaymentBluepayRedirect
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentWorldpay getAdminModelExtensionPaymentWorldpay
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentRealexRemote getAdminModelExtensionPaymentRealexRemote
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentEway getAdminModelExtensionPaymentEway
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentCardinity getAdminModelExtensionPaymentCardinity
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentG2apay getAdminModelExtensionPaymentG2apay
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentAmazonLoginPay getAdminModelExtensionPaymentAmazonLoginPay
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentGlobalpayRemote getAdminModelExtensionPaymentGlobalpayRemote
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentGlobalpay getAdminModelExtensionPaymentGlobalpay
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentPilibaba getAdminModelExtensionPaymentPilibaba
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentSecuretradingPp getAdminModelExtensionPaymentSecuretradingPp
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentPpProIframe getAdminModelExtensionPaymentPpProIframe
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentSagepayServer getAdminModelExtensionPaymentSagepayServer
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentSecuretradingWs getAdminModelExtensionPaymentSecuretradingWs
 * @method \OpencartApi\Models\v3037\AdminModelExtensionPaymentRealex getAdminModelExtensionPaymentRealex
 * @method \OpencartApi\Models\v3037\AdminModelExtensionDashboardMap getAdminModelExtensionDashboardMap
 * @method \OpencartApi\Models\v3037\AdminModelExtensionDashboardSale getAdminModelExtensionDashboardSale
 * @method \OpencartApi\Models\v3037\AdminModelExtensionDashboardActivity getAdminModelExtensionDashboardActivity
 * @method \OpencartApi\Models\v3037\AdminModelExtensionDashboardOnline getAdminModelExtensionDashboardOnline
 * @method \OpencartApi\Models\v3037\AdminModelExtensionDashboardChart getAdminModelExtensionDashboardChart
 * @method \OpencartApi\Models\v3037\AdminModelExtensionReportSale getAdminModelExtensionReportSale
 * @method \OpencartApi\Models\v3037\AdminModelExtensionReportCustomer getAdminModelExtensionReportCustomer
 * @method \OpencartApi\Models\v3037\AdminModelExtensionReportActivity getAdminModelExtensionReportActivity
 * @method \OpencartApi\Models\v3037\AdminModelExtensionReportCoupon getAdminModelExtensionReportCoupon
 * @method \OpencartApi\Models\v3037\AdminModelExtensionReportProduct getAdminModelExtensionReportProduct
 * @method \OpencartApi\Models\v3037\AdminModelExtensionReportReturn getAdminModelExtensionReportReturn
 * @method \OpencartApi\Models\v3037\AdminModelExtensionReportMarketing getAdminModelExtensionReportMarketing
 * @method \OpencartApi\Models\v3037\AdminModelExtensionReportCustomerTransaction getAdminModelExtensionReportCustomerTransaction
 * @method \OpencartApi\Models\v3037\AdminModelLocalisationZone getAdminModelLocalisationZone
 * @method \OpencartApi\Models\v3037\AdminModelLocalisationLanguage getAdminModelLocalisationLanguage
 * @method \OpencartApi\Models\v3037\AdminModelLocalisationStockStatus getAdminModelLocalisationStockStatus
 * @method \OpencartApi\Models\v3037\AdminModelLocalisationLengthClass getAdminModelLocalisationLengthClass
 * @method \OpencartApi\Models\v3037\AdminModelLocalisationReturnStatus getAdminModelLocalisationReturnStatus
 * @method \OpencartApi\Models\v3037\AdminModelLocalisationTaxClass getAdminModelLocalisationTaxClass
 * @method \OpencartApi\Models\v3037\AdminModelLocalisationReturnReason getAdminModelLocalisationReturnReason
 * @method \OpencartApi\Models\v3037\AdminModelLocalisationWeightClass getAdminModelLocalisationWeightClass
 * @method \OpencartApi\Models\v3037\AdminModelLocalisationGeoZone getAdminModelLocalisationGeoZone
 * @method \OpencartApi\Models\v3037\AdminModelLocalisationCurrency getAdminModelLocalisationCurrency
 * @method \OpencartApi\Models\v3037\AdminModelLocalisationCountry getAdminModelLocalisationCountry
 * @method \OpencartApi\Models\v3037\AdminModelLocalisationTaxRate getAdminModelLocalisationTaxRate
 * @method \OpencartApi\Models\v3037\AdminModelLocalisationOrderStatus getAdminModelLocalisationOrderStatus
 * @method \OpencartApi\Models\v3037\AdminModelLocalisationLocation getAdminModelLocalisationLocation
 * @method \OpencartApi\Models\v3037\AdminModelLocalisationReturnAction getAdminModelLocalisationReturnAction
 * @method \OpencartApi\Models\v3037\AdminModelUserApi getAdminModelUserApi
 * @method \OpencartApi\Models\v3037\AdminModelUserUser getAdminModelUserUser
 * @method \OpencartApi\Models\v3037\AdminModelUserUserGroup getAdminModelUserUserGroup
 * @method \OpencartApi\Models\v3037\AdminModelDesignBanner getAdminModelDesignBanner
 * @method \OpencartApi\Models\v3037\AdminModelDesignLayout getAdminModelDesignLayout
 * @method \OpencartApi\Models\v3037\AdminModelDesignTranslation getAdminModelDesignTranslation
 * @method \OpencartApi\Models\v3037\AdminModelDesignSeoUrl getAdminModelDesignSeoUrl
 * @method \OpencartApi\Models\v3037\AdminModelDesignTheme getAdminModelDesignTheme
 * @method \OpencartApi\Models\v3037\AdminModelReportOnline getAdminModelReportOnline
 * @method \OpencartApi\Models\v3037\AdminModelReportStatistics getAdminModelReportStatistics
 * @method \OpencartApi\Models\v3037\AdminModelCustomerCustomerApproval getAdminModelCustomerCustomerApproval
 * @method \OpencartApi\Models\v3037\AdminModelCustomerCustomer getAdminModelCustomerCustomer
 * @method \OpencartApi\Models\v3037\AdminModelCustomerCustomerGroup getAdminModelCustomerCustomerGroup
 * @method \OpencartApi\Models\v3037\AdminModelCustomerCustomField getAdminModelCustomerCustomField
 */
trait OpencartModelsTrait
{
    
}