<?php


namespace OpencartApi\ModelContainer\v3020;


use OpencartApi\Base\BaseModel;

/**
 * Trait OpencartModelsTrait
 *
 * @method \OpencartApi\Models\v3020\ModelCheckoutOrder getModelCheckoutOrder
 * @method \OpencartApi\Models\v3020\ModelCheckoutRecurring getModelCheckoutRecurring
 * @method \OpencartApi\Models\v3020\ModelCheckoutMarketing getModelCheckoutMarketing
 * @method \OpencartApi\Models\v3020\ModelToolImage getModelToolImage
 * @method \OpencartApi\Models\v3020\ModelToolOnline getModelToolOnline
 * @method \OpencartApi\Models\v3020\ModelToolUpload getModelToolUpload
 * @method \OpencartApi\Models\v3020\ModelSettingApi getModelSettingApi
 * @method \OpencartApi\Models\v3020\ModelSettingSetting getModelSettingSetting
 * @method \OpencartApi\Models\v3020\ModelSettingStore getModelSettingStore
 * @method \OpencartApi\Models\v3020\ModelSettingModule getModelSettingModule
 * @method \OpencartApi\Models\v3020\ModelSettingExtension getModelSettingExtension
 * @method \OpencartApi\Models\v3020\ModelSettingEvent getModelSettingEvent
 * @method \OpencartApi\Models\v3020\ModelAccountOrder getModelAccountOrder
 * @method \OpencartApi\Models\v3020\ModelAccountApi getModelAccountApi
 * @method \OpencartApi\Models\v3020\ModelAccountAddress getModelAccountAddress
 * @method \OpencartApi\Models\v3020\ModelAccountReward getModelAccountReward
 * @method \OpencartApi\Models\v3020\ModelAccountCustomer getModelAccountCustomer
 * @method \OpencartApi\Models\v3020\ModelAccountTransaction getModelAccountTransaction
 * @method \OpencartApi\Models\v3020\ModelAccountActivity getModelAccountActivity
 * @method \OpencartApi\Models\v3020\ModelAccountCustomerGroup getModelAccountCustomerGroup
 * @method \OpencartApi\Models\v3020\ModelAccountWishlist getModelAccountWishlist
 * @method \OpencartApi\Models\v3020\ModelAccountRecurring getModelAccountRecurring
 * @method \OpencartApi\Models\v3020\ModelAccountCustomField getModelAccountCustomField
 * @method \OpencartApi\Models\v3020\ModelAccountDownload getModelAccountDownload
 * @method \OpencartApi\Models\v3020\ModelAccountReturn getModelAccountReturn
 * @method \OpencartApi\Models\v3020\ModelAccountSearch getModelAccountSearch
 * @method \OpencartApi\Models\v3020\ModelCatalogCategory getModelCatalogCategory
 * @method \OpencartApi\Models\v3020\ModelCatalogManufacturer getModelCatalogManufacturer
 * @method \OpencartApi\Models\v3020\ModelCatalogProduct getModelCatalogProduct
 * @method \OpencartApi\Models\v3020\ModelCatalogReview getModelCatalogReview
 * @method \OpencartApi\Models\v3020\ModelCatalogInformation getModelCatalogInformation
 * @method \OpencartApi\Models\v3020\ModelExtensionFeedGoogleBase getModelExtensionFeedGoogleBase
 * @method \OpencartApi\Models\v3020\ModelExtensionCreditCardSquareup getModelExtensionCreditCardSquareup
 * @method \OpencartApi\Models\v3020\ModelExtensionModuleLaybuyLayout getModelExtensionModuleLaybuyLayout
 * @method \OpencartApi\Models\v3020\ModelExtensionModulePpLogin getModelExtensionModulePpLogin
 * @method \OpencartApi\Models\v3020\ModelExtensionOpenbayAmazonusOrder getModelExtensionOpenbayAmazonusOrder
 * @method \OpencartApi\Models\v3020\ModelExtensionOpenbayEtsyOrder getModelExtensionOpenbayEtsyOrder
 * @method \OpencartApi\Models\v3020\ModelExtensionOpenbayAmazonusListing getModelExtensionOpenbayAmazonusListing
 * @method \OpencartApi\Models\v3020\ModelExtensionOpenbayAmazonusProduct getModelExtensionOpenbayAmazonusProduct
 * @method \OpencartApi\Models\v3020\ModelExtensionOpenbayEtsyProduct getModelExtensionOpenbayEtsyProduct
 * @method \OpencartApi\Models\v3020\ModelExtensionOpenbayAmazonListing getModelExtensionOpenbayAmazonListing
 * @method \OpencartApi\Models\v3020\ModelExtensionOpenbayAmazonProduct getModelExtensionOpenbayAmazonProduct
 * @method \OpencartApi\Models\v3020\ModelExtensionOpenbayEbayOrder getModelExtensionOpenbayEbayOrder
 * @method \OpencartApi\Models\v3020\ModelExtensionOpenbayEbayProduct getModelExtensionOpenbayEbayProduct
 * @method \OpencartApi\Models\v3020\ModelExtensionOpenbayAmazonOrder getModelExtensionOpenbayAmazonOrder
 * @method \OpencartApi\Models\v3020\ModelExtensionTotalKlarnaFee getModelExtensionTotalKlarnaFee
 * @method \OpencartApi\Models\v3020\ModelExtensionTotalReward getModelExtensionTotalReward
 * @method \OpencartApi\Models\v3020\ModelExtensionTotalCoupon getModelExtensionTotalCoupon
 * @method \OpencartApi\Models\v3020\ModelExtensionTotalLowOrderFee getModelExtensionTotalLowOrderFee
 * @method \OpencartApi\Models\v3020\ModelExtensionTotalCredit getModelExtensionTotalCredit
 * @method \OpencartApi\Models\v3020\ModelExtensionTotalTax getModelExtensionTotalTax
 * @method \OpencartApi\Models\v3020\ModelExtensionTotalVoucherTheme getModelExtensionTotalVoucherTheme
 * @method \OpencartApi\Models\v3020\ModelExtensionTotalTotal getModelExtensionTotalTotal
 * @method \OpencartApi\Models\v3020\ModelExtensionTotalShipping getModelExtensionTotalShipping
 * @method \OpencartApi\Models\v3020\ModelExtensionTotalSubTotal getModelExtensionTotalSubTotal
 * @method \OpencartApi\Models\v3020\ModelExtensionTotalHandling getModelExtensionTotalHandling
 * @method \OpencartApi\Models\v3020\ModelExtensionTotalVoucher getModelExtensionTotalVoucher
 * @method \OpencartApi\Models\v3020\ModelExtensionFraudMaxmind getModelExtensionFraudMaxmind
 * @method \OpencartApi\Models\v3020\ModelExtensionFraudIp getModelExtensionFraudIp
 * @method \OpencartApi\Models\v3020\ModelExtensionFraudFraudlabspro getModelExtensionFraudFraudlabspro
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentPpBraintree getModelExtensionPaymentPpBraintree
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentKlarnaCheckout getModelExtensionPaymentKlarnaCheckout
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentPerpetualPayments getModelExtensionPaymentPerpetualPayments
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentFirstdata getModelExtensionPaymentFirstdata
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentNochex getModelExtensionPaymentNochex
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentLaybuy getModelExtensionPaymentLaybuy
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentLiqpay getModelExtensionPaymentLiqpay
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentSagepayDirect getModelExtensionPaymentSagepayDirect
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentCheque getModelExtensionPaymentCheque
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentDivido getModelExtensionPaymentDivido
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentFirstdataRemote getModelExtensionPaymentFirstdataRemote
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentBluepayHosted getModelExtensionPaymentBluepayHosted
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentWebPaymentSoftware getModelExtensionPaymentWebPaymentSoftware
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentSkrill getModelExtensionPaymentSkrill
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentWechatPay getModelExtensionPaymentWechatPay
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentTwocheckout getModelExtensionPaymentTwocheckout
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentCardconnect getModelExtensionPaymentCardconnect
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentPpStandard getModelExtensionPaymentPpStandard
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentFreeCheckout getModelExtensionPaymentFreeCheckout
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentPaymate getModelExtensionPaymentPaymate
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentSquareup getModelExtensionPaymentSquareup
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentPpExpress getModelExtensionPaymentPpExpress
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentPpPayflowIframe getModelExtensionPaymentPpPayflowIframe
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentBluepayRedirect getModelExtensionPaymentBluepayRedirect
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentWorldpay getModelExtensionPaymentWorldpay
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentRealexRemote getModelExtensionPaymentRealexRemote
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentCod getModelExtensionPaymentCod
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentEway getModelExtensionPaymentEway
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentCardinity getModelExtensionPaymentCardinity
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentSagepayUs getModelExtensionPaymentSagepayUs
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentAuthorizenetSim getModelExtensionPaymentAuthorizenetSim
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentPpPro getModelExtensionPaymentPpPro
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentPayza getModelExtensionPaymentPayza
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentG2apay getModelExtensionPaymentG2apay
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentPaypoint getModelExtensionPaymentPaypoint
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentAmazonLoginPay getModelExtensionPaymentAmazonLoginPay
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentGlobalpayRemote getModelExtensionPaymentGlobalpayRemote
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentGlobalpay getModelExtensionPaymentGlobalpay
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentAlipayCross getModelExtensionPaymentAlipayCross
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentKlarnaAccount getModelExtensionPaymentKlarnaAccount
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentPilibaba getModelExtensionPaymentPilibaba
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentSecuretradingPp getModelExtensionPaymentSecuretradingPp
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentBankTransfer getModelExtensionPaymentBankTransfer
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentPpProIframe getModelExtensionPaymentPpProIframe
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentKlarnaInvoice getModelExtensionPaymentKlarnaInvoice
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentSagepayServer getModelExtensionPaymentSagepayServer
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentAlipay getModelExtensionPaymentAlipay
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentAuthorizenetAim getModelExtensionPaymentAuthorizenetAim
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentSecuretradingWs getModelExtensionPaymentSecuretradingWs
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentPpPayflow getModelExtensionPaymentPpPayflow
 * @method \OpencartApi\Models\v3020\ModelExtensionPaymentRealex getModelExtensionPaymentRealex
 * @method \OpencartApi\Models\v3020\ModelExtensionShippingFedex getModelExtensionShippingFedex
 * @method \OpencartApi\Models\v3020\ModelExtensionShippingUsps getModelExtensionShippingUsps
 * @method \OpencartApi\Models\v3020\ModelExtensionShippingUps getModelExtensionShippingUps
 * @method \OpencartApi\Models\v3020\ModelExtensionShippingFree getModelExtensionShippingFree
 * @method \OpencartApi\Models\v3020\ModelExtensionShippingCitylink getModelExtensionShippingCitylink
 * @method \OpencartApi\Models\v3020\ModelExtensionShippingEcShip getModelExtensionShippingEcShip
 * @method \OpencartApi\Models\v3020\ModelExtensionShippingRoyalMail getModelExtensionShippingRoyalMail
 * @method \OpencartApi\Models\v3020\ModelExtensionShippingFlat getModelExtensionShippingFlat
 * @method \OpencartApi\Models\v3020\ModelExtensionShippingItem getModelExtensionShippingItem
 * @method \OpencartApi\Models\v3020\ModelExtensionShippingAuspost getModelExtensionShippingAuspost
 * @method \OpencartApi\Models\v3020\ModelExtensionShippingPilibaba getModelExtensionShippingPilibaba
 * @method \OpencartApi\Models\v3020\ModelExtensionShippingPickup getModelExtensionShippingPickup
 * @method \OpencartApi\Models\v3020\ModelExtensionShippingWeight getModelExtensionShippingWeight
 * @method \OpencartApi\Models\v3020\ModelExtensionShippingParcelforce48 getModelExtensionShippingParcelforce48
 * @method \OpencartApi\Models\v3020\ModelLocalisationZone getModelLocalisationZone
 * @method \OpencartApi\Models\v3020\ModelLocalisationLanguage getModelLocalisationLanguage
 * @method \OpencartApi\Models\v3020\ModelLocalisationReturnReason getModelLocalisationReturnReason
 * @method \OpencartApi\Models\v3020\ModelLocalisationCurrency getModelLocalisationCurrency
 * @method \OpencartApi\Models\v3020\ModelLocalisationCountry getModelLocalisationCountry
 * @method \OpencartApi\Models\v3020\ModelLocalisationOrderStatus getModelLocalisationOrderStatus
 * @method \OpencartApi\Models\v3020\ModelLocalisationLocation getModelLocalisationLocation
 * @method \OpencartApi\Models\v3020\ModelDesignBanner getModelDesignBanner
 * @method \OpencartApi\Models\v3020\ModelDesignLayout getModelDesignLayout
 * @method \OpencartApi\Models\v3020\ModelDesignTranslation getModelDesignTranslation
 * @method \OpencartApi\Models\v3020\ModelDesignTheme getModelDesignTheme
 * @method \OpencartApi\Models\v3020\ModelReportStatistics getModelReportStatistics
 * @method \OpencartApi\Models\v3020\AdminModelSaleOrder getAdminModelSaleOrder
 * @method \OpencartApi\Models\v3020\AdminModelSaleRecurring getAdminModelSaleRecurring
 * @method \OpencartApi\Models\v3020\AdminModelSaleVoucherTheme getAdminModelSaleVoucherTheme
 * @method \OpencartApi\Models\v3020\AdminModelSaleReturn getAdminModelSaleReturn
 * @method \OpencartApi\Models\v3020\AdminModelSaleVoucher getAdminModelSaleVoucher
 * @method \OpencartApi\Models\v3020\AdminModelToolImage getAdminModelToolImage
 * @method \OpencartApi\Models\v3020\AdminModelToolUpload getAdminModelToolUpload
 * @method \OpencartApi\Models\v3020\AdminModelToolBackup getAdminModelToolBackup
 * @method \OpencartApi\Models\v3020\AdminModelSettingSetting getAdminModelSettingSetting
 * @method \OpencartApi\Models\v3020\AdminModelSettingStore getAdminModelSettingStore
 * @method \OpencartApi\Models\v3020\AdminModelSettingModule getAdminModelSettingModule
 * @method \OpencartApi\Models\v3020\AdminModelSettingExtension getAdminModelSettingExtension
 * @method \OpencartApi\Models\v3020\AdminModelSettingEvent getAdminModelSettingEvent
 * @method \OpencartApi\Models\v3020\AdminModelSettingModification getAdminModelSettingModification
 * @method \OpencartApi\Models\v3020\AdminModelCatalogCategory getAdminModelCatalogCategory
 * @method \OpencartApi\Models\v3020\AdminModelCatalogAttributeGroup getAdminModelCatalogAttributeGroup
 * @method \OpencartApi\Models\v3020\AdminModelCatalogManufacturer getAdminModelCatalogManufacturer
 * @method \OpencartApi\Models\v3020\AdminModelCatalogOption getAdminModelCatalogOption
 * @method \OpencartApi\Models\v3020\AdminModelCatalogProduct getAdminModelCatalogProduct
 * @method \OpencartApi\Models\v3020\AdminModelCatalogRecurring getAdminModelCatalogRecurring
 * @method \OpencartApi\Models\v3020\AdminModelCatalogDownload getAdminModelCatalogDownload
 * @method \OpencartApi\Models\v3020\AdminModelCatalogAttribute getAdminModelCatalogAttribute
 * @method \OpencartApi\Models\v3020\AdminModelCatalogReview getAdminModelCatalogReview
 * @method \OpencartApi\Models\v3020\AdminModelCatalogFilter getAdminModelCatalogFilter
 * @method \OpencartApi\Models\v3020\AdminModelCatalogInformation getAdminModelCatalogInformation
 * @method \OpencartApi\Models\v3020\AdminModelMarketingCoupon getAdminModelMarketingCoupon
 * @method \OpencartApi\Models\v3020\AdminModelMarketingMarketing getAdminModelMarketingMarketing
 * @method \OpencartApi\Models\v3020\AdminModelExtensionFeedGoogleBase getAdminModelExtensionFeedGoogleBase
 * @method \OpencartApi\Models\v3020\AdminModelExtensionOpenbayOrder getAdminModelExtensionOpenbayOrder
 * @method \OpencartApi\Models\v3020\AdminModelExtensionOpenbayAmazonusListing getAdminModelExtensionOpenbayAmazonusListing
 * @method \OpencartApi\Models\v3020\AdminModelExtensionOpenbayEtsyProduct getAdminModelExtensionOpenbayEtsyProduct
 * @method \OpencartApi\Models\v3020\AdminModelExtensionOpenbayAmazonListing getAdminModelExtensionOpenbayAmazonListing
 * @method \OpencartApi\Models\v3020\AdminModelExtensionOpenbayFba getAdminModelExtensionOpenbayFba
 * @method \OpencartApi\Models\v3020\AdminModelExtensionOpenbayEtsy getAdminModelExtensionOpenbayEtsy
 * @method \OpencartApi\Models\v3020\AdminModelExtensionOpenbayEbay getAdminModelExtensionOpenbayEbay
 * @method \OpencartApi\Models\v3020\AdminModelExtensionOpenbayEbayProduct getAdminModelExtensionOpenbayEbayProduct
 * @method \OpencartApi\Models\v3020\AdminModelExtensionOpenbayAmazon getAdminModelExtensionOpenbayAmazon
 * @method \OpencartApi\Models\v3020\AdminModelExtensionOpenbayOpenbay getAdminModelExtensionOpenbayOpenbay
 * @method \OpencartApi\Models\v3020\AdminModelExtensionOpenbayAmazonus getAdminModelExtensionOpenbayAmazonus
 * @method \OpencartApi\Models\v3020\AdminModelExtensionOpenbayEbayProfile getAdminModelExtensionOpenbayEbayProfile
 * @method \OpencartApi\Models\v3020\AdminModelExtensionOpenbayEbayTemplate getAdminModelExtensionOpenbayEbayTemplate
 * @method \OpencartApi\Models\v3020\AdminModelExtensionOpenbayVersion getAdminModelExtensionOpenbayVersion
 * @method \OpencartApi\Models\v3020\AdminModelExtensionFraudMaxmind getAdminModelExtensionFraudMaxmind
 * @method \OpencartApi\Models\v3020\AdminModelExtensionFraudIp getAdminModelExtensionFraudIp
 * @method \OpencartApi\Models\v3020\AdminModelExtensionFraudFraudlabspro getAdminModelExtensionFraudFraudlabspro
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentPpBraintree getAdminModelExtensionPaymentPpBraintree
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentKlarnaCheckout getAdminModelExtensionPaymentKlarnaCheckout
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentFirstdata getAdminModelExtensionPaymentFirstdata
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentLaybuy getAdminModelExtensionPaymentLaybuy
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentSagepayDirect getAdminModelExtensionPaymentSagepayDirect
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentDivido getAdminModelExtensionPaymentDivido
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentFirstdataRemote getAdminModelExtensionPaymentFirstdataRemote
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentBluepayHosted getAdminModelExtensionPaymentBluepayHosted
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentCardconnect getAdminModelExtensionPaymentCardconnect
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentSquareup getAdminModelExtensionPaymentSquareup
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentPpExpress getAdminModelExtensionPaymentPpExpress
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentPpPayflowIframe getAdminModelExtensionPaymentPpPayflowIframe
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentBluepayRedirect getAdminModelExtensionPaymentBluepayRedirect
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentWorldpay getAdminModelExtensionPaymentWorldpay
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentRealexRemote getAdminModelExtensionPaymentRealexRemote
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentEway getAdminModelExtensionPaymentEway
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentCardinity getAdminModelExtensionPaymentCardinity
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentG2apay getAdminModelExtensionPaymentG2apay
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentAmazonLoginPay getAdminModelExtensionPaymentAmazonLoginPay
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentGlobalpayRemote getAdminModelExtensionPaymentGlobalpayRemote
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentGlobalpay getAdminModelExtensionPaymentGlobalpay
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentPilibaba getAdminModelExtensionPaymentPilibaba
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentSecuretradingPp getAdminModelExtensionPaymentSecuretradingPp
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentPpProIframe getAdminModelExtensionPaymentPpProIframe
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentSagepayServer getAdminModelExtensionPaymentSagepayServer
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentSecuretradingWs getAdminModelExtensionPaymentSecuretradingWs
 * @method \OpencartApi\Models\v3020\AdminModelExtensionPaymentRealex getAdminModelExtensionPaymentRealex
 * @method \OpencartApi\Models\v3020\AdminModelExtensionDashboardMap getAdminModelExtensionDashboardMap
 * @method \OpencartApi\Models\v3020\AdminModelExtensionDashboardSale getAdminModelExtensionDashboardSale
 * @method \OpencartApi\Models\v3020\AdminModelExtensionDashboardActivity getAdminModelExtensionDashboardActivity
 * @method \OpencartApi\Models\v3020\AdminModelExtensionDashboardOnline getAdminModelExtensionDashboardOnline
 * @method \OpencartApi\Models\v3020\AdminModelExtensionDashboardChart getAdminModelExtensionDashboardChart
 * @method \OpencartApi\Models\v3020\AdminModelExtensionReportSale getAdminModelExtensionReportSale
 * @method \OpencartApi\Models\v3020\AdminModelExtensionReportCustomer getAdminModelExtensionReportCustomer
 * @method \OpencartApi\Models\v3020\AdminModelExtensionReportActivity getAdminModelExtensionReportActivity
 * @method \OpencartApi\Models\v3020\AdminModelExtensionReportCoupon getAdminModelExtensionReportCoupon
 * @method \OpencartApi\Models\v3020\AdminModelExtensionReportProduct getAdminModelExtensionReportProduct
 * @method \OpencartApi\Models\v3020\AdminModelExtensionReportReturn getAdminModelExtensionReportReturn
 * @method \OpencartApi\Models\v3020\AdminModelExtensionReportMarketing getAdminModelExtensionReportMarketing
 * @method \OpencartApi\Models\v3020\AdminModelExtensionReportCustomerTransaction getAdminModelExtensionReportCustomerTransaction
 * @method \OpencartApi\Models\v3020\AdminModelLocalisationZone getAdminModelLocalisationZone
 * @method \OpencartApi\Models\v3020\AdminModelLocalisationLanguage getAdminModelLocalisationLanguage
 * @method \OpencartApi\Models\v3020\AdminModelLocalisationStockStatus getAdminModelLocalisationStockStatus
 * @method \OpencartApi\Models\v3020\AdminModelLocalisationLengthClass getAdminModelLocalisationLengthClass
 * @method \OpencartApi\Models\v3020\AdminModelLocalisationReturnStatus getAdminModelLocalisationReturnStatus
 * @method \OpencartApi\Models\v3020\AdminModelLocalisationTaxClass getAdminModelLocalisationTaxClass
 * @method \OpencartApi\Models\v3020\AdminModelLocalisationReturnReason getAdminModelLocalisationReturnReason
 * @method \OpencartApi\Models\v3020\AdminModelLocalisationWeightClass getAdminModelLocalisationWeightClass
 * @method \OpencartApi\Models\v3020\AdminModelLocalisationGeoZone getAdminModelLocalisationGeoZone
 * @method \OpencartApi\Models\v3020\AdminModelLocalisationCurrency getAdminModelLocalisationCurrency
 * @method \OpencartApi\Models\v3020\AdminModelLocalisationCountry getAdminModelLocalisationCountry
 * @method \OpencartApi\Models\v3020\AdminModelLocalisationTaxRate getAdminModelLocalisationTaxRate
 * @method \OpencartApi\Models\v3020\AdminModelLocalisationOrderStatus getAdminModelLocalisationOrderStatus
 * @method \OpencartApi\Models\v3020\AdminModelLocalisationLocation getAdminModelLocalisationLocation
 * @method \OpencartApi\Models\v3020\AdminModelLocalisationReturnAction getAdminModelLocalisationReturnAction
 * @method \OpencartApi\Models\v3020\AdminModelUserApi getAdminModelUserApi
 * @method \OpencartApi\Models\v3020\AdminModelUserUser getAdminModelUserUser
 * @method \OpencartApi\Models\v3020\AdminModelUserUserGroup getAdminModelUserUserGroup
 * @method \OpencartApi\Models\v3020\AdminModelDesignBanner getAdminModelDesignBanner
 * @method \OpencartApi\Models\v3020\AdminModelDesignLayout getAdminModelDesignLayout
 * @method \OpencartApi\Models\v3020\AdminModelDesignTranslation getAdminModelDesignTranslation
 * @method \OpencartApi\Models\v3020\AdminModelDesignSeoUrl getAdminModelDesignSeoUrl
 * @method \OpencartApi\Models\v3020\AdminModelDesignTheme getAdminModelDesignTheme
 * @method \OpencartApi\Models\v3020\AdminModelReportOnline getAdminModelReportOnline
 * @method \OpencartApi\Models\v3020\AdminModelReportStatistics getAdminModelReportStatistics
 * @method \OpencartApi\Models\v3020\AdminModelCustomerCustomerApproval getAdminModelCustomerCustomerApproval
 * @method \OpencartApi\Models\v3020\AdminModelCustomerCustomer getAdminModelCustomerCustomer
 * @method \OpencartApi\Models\v3020\AdminModelCustomerCustomerGroup getAdminModelCustomerCustomerGroup
 * @method \OpencartApi\Models\v3020\AdminModelCustomerCustomField getAdminModelCustomerCustomField
 */
trait OpencartModelsTrait
{
    
}